# Generated by Django 4.2.30 on 2026-07-23 07:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_classroom_feestructure_section_student_subject_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('school_created', 'School Created'), ('school_status_changed', 'School Status Changed'), ('plan_changed', 'Plan Changed'), ('admin_assigned', 'Admin Assigned'), ('login_failed', 'Login Failed'), ('user_status_changed', 'User Status Changed')], max_length=35)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='performed_activities', to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities', to='core.school')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
