# Generated by Django 4.2.30 on 2026-07-23 09:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_platformactivity'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('price_month', models.DecimalField(decimal_places=2, default=0, help_text='Monthly price in USD. Set to 0 for free plans.', max_digits=10)),
                ('student_limit', models.PositiveIntegerField(blank=True, help_text='Maximum students allowed. Leave blank for Unlimited.', null=True)),
                ('staff_limit', models.PositiveIntegerField(blank=True, help_text='Maximum staff members allowed. Leave blank for Unlimited.', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Only active plans are selectable when assigning to a school.')),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order in lists (lower = shown first).')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='school',
            name='subscription_plan',
            field=models.ForeignKey(blank=True, help_text='The active subscription plan for this school. Overrides the legacy plan field.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schools', to='core.subscriptionplan'),
        ),
    ]
