# Generated by Django 4.2.30 on 2026-07-27 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_syllabus_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='currency',
            field=models.CharField(choices=[('USD', 'US Dollar ($)'), ('EUR', 'Euro (€)'), ('GBP', 'British Pound (£)'), ('PKR', 'Pakistani Rupee (Rs)'), ('INR', 'Indian Rupee (₹)'), ('AED', 'UAE Dirham (AED)'), ('SAR', 'Saudi Riyal (SAR)'), ('CAD', 'Canadian Dollar (C$)'), ('AUD', 'Australian Dollar (A$)')], default='USD', help_text='Currency used for fee invoices at this school.', max_length=3),
        ),
        migrations.AddField(
            model_name='school',
            name='theme_color',
            field=models.CharField(choices=[('indigo', 'Indigo'), ('blue', 'Blue'), ('teal', 'Teal'), ('emerald', 'Emerald'), ('rose', 'Rose'), ('amber', 'Amber'), ('violet', 'Violet'), ('slate', 'Slate')], default='indigo', help_text='Primary brand color for the school portal UI.', max_length=20),
        ),
    ]
