# Generated by Django 4.2.30 on 2026-07-30 10:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_homework_diary'),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField()),
                ('priority', models.CharField(choices=[('normal', 'Normal'), ('important', 'Important'), ('urgent', 'Urgent')], default='normal', max_length=20)),
                ('audience', models.CharField(choices=[('all', 'Entire School'), ('students', 'All Students'), ('parents', 'All Parents'), ('teachers', 'All Teachers'), ('staff', 'All Staff'), ('section', 'Specific Section')], default='all', max_length=20)),
                ('is_pinned', models.BooleanField(default=False, help_text='Pinned announcements always appear at the top.')),
                ('expires_at', models.DateTimeField(blank=True, help_text='Auto-hide after this date/time. Leave blank for no expiry.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authored_announcements', to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.school')),
                ('section', models.ForeignKey(blank=True, help_text='Required only when audience is "Specific Section".', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='announcements', to='core.section')),
            ],
            options={
                'ordering': ['-is_pinned', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AnnouncementReadReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('read_at', models.DateTimeField(auto_now_add=True)),
                ('announcement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='read_receipts', to='core.announcement')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='announcement_reads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-read_at'],
                'unique_together': {('announcement', 'user')},
            },
        ),
    ]
